import type { Building } from '@/types/building'

export const BUILDINGS: Building[] = [
  {
    id: 'about',
    label: 'About',
    sub: 'Identity',
    tag: '01 — IDENTITY',
    panelTitle: 'Diego<br><span>Chávez</span>',
    body: 'Full-Stack Engineer & DevOps based in Mexico City. I build products end-to-end — from pixel-perfect interfaces to production-ready infrastructure. I don\'t just write code, I ship it reliably.\n\nCurrently co-founding a tech consultancy, leading frontend and infrastructure for a major financial institution client.',
    stack: ['Next.js 14', 'React', 'TypeScript', 'Styled Components', 'Docker', 'Linux'],
    items: [],
    gx: -3.5, gy: -2,
    gw: 2.2, gd: 1.6,
    floors: 6, h: 160,
    col: '#f5a623',
  },
  {
    id: 'projects',
    label: 'Projects',
    sub: 'Built from Scratch',
    tag: '02 — PROJECTS',
    panelTitle: 'Built from<br><span>Scratch</span>',
    body: 'Products I designed and built with full ownership — from database schema to production deploy.',
    stack: [],
    items: [
      {
        title: 'Dusk',
        desc: 'Social platform for location-based networking. H3 geolocation, Supabase RLS, Edge Functions, Twilio OTP. Built solo.',
        stack: ['Next.js', 'Supabase', 'H3', 'Twilio'],
        screenshots: [
                      "/projects/dusk/1.png",
                      "/projects/dusk/2.png",
                      "/projects/dusk/3.png",
                      "/projects/dusk/4.png",
                      "/projects/dusk/5.png",
                      "/projects/dusk/6.png",
                      "/projects/dusk/7.png",
                    ]
      },
      {
        title: 'Forge',
        desc: 'AI-powered e-learning platform with LLM tutoring. Next.js 14 + Supabase + Ollama/Gemini.',
        stack: ['Next.js 14', 'Supabase', 'Ollama', 'Gemini'],
        screenshots: [
                      "/projects/forge/1.png",
                      "/projects/forge/2.png",
                      "/projects/forge/3.png",
                      "/projects/forge/4.png",
                      "/projects/forge/5.png",
                      "/projects/forge/6.png",
                      "/projects/forge/7.png",
                      "/projects/forge/8.png",
                      "/projects/forge/9.png",
                      "/projects/forge/10.png",
                    ]
        
      },
      {
        title: 'RAREB',
        desc: 'Biometric attendance system for university faculty. Facial & fingerprint recognition via .NET APIs.',
        stack: ['Next.js', 'NextAuth', '.NET', 'SQL Server'],
      },
    ],
    gx: 0.2, gy: -3.2,
    gw: 2.6, gd: 1.8,
    floors: 9, h: 210,
    col: '#ffd060',
  },
  {
    id: 'devops',
    label: 'DevOps',
    sub: 'Infrastructure',
    tag: '03 — INFRASTRUCTURE',
    panelTitle: 'Ship it<br><span>Reliably</span>',
    body: 'I build the pipes that keep software running. CI/CD pipelines from scratch, containerized environments, automated deployments — zero manual intervention in production.',
    stack: ['Jenkins', 'Gitea', 'Docker', 'Linux', 'VPS', 'Nginx', 'Semantic Versioning'],
    items: [
      {
        title: 'CI/CD Pipelines',
        desc: 'Complete pipelines for two production apps with semantic versioning, multi-environment Docker tagging and .env-based deploy strategies.',
        stack: ['Jenkins', 'Gitea', 'Docker'],
      },
      {
        title: 'Private Registry',
        desc: 'Self-hosted Docker registry with authentication and automated image pruning.',
        stack: ['Docker', 'Linux', 'Nginx'],
      },
    ],
    gx: 3.2, gy: -1.5,
    gw: 2.0, gd: 1.5,
    floors: 5, h: 130,
    col: '#b87000',
  },
  {
    id: 'experience',
    label: 'Experience',
    sub: '6 Years Shipping',
    tag: '04 — EXPERIENCE',
    panelTitle: 'Built &<br><span>Delivered</span>',
    body: "From tech lead at Mexico's top engineering university to co-founding a consultancy. I've built systems used daily by thousands of people — and products from zero to production.",
    stack: [],
    items: [
      {
        title: 'Co-Founder & CTO — Consultancy',
        period: '2025 — Present',
        desc: 'Co-founded a tech consultancy with institutional clients. Leading all technical architecture, infrastructure and product decisions.',
        stack: ['Next.js 14', 'Supabase', 'Docker', 'NestJS', 'PostgreSQL'],
        deliverables: [
          {
            title: 'Forge — AI E-learning Platform',
            desc: "AI-powered e-learning platform for Mexico's JCF government program. Built solo — multi-tenant architecture, LLM tutoring, Supabase backend with RLS policies.",
            stack: ['Next.js 14', 'Supabase', 'Ollama', 'Gemini'],
            screenshots: [
              '/projects/forge/1.png',
              '/projects/forge/2.png',
              '/projects/forge/3.png',
              '/projects/forge/4.png',
            ],
          },
          {
            title: 'Dinetik — Financial Education App',
            desc: "Native mobile financial education platform for Banamex and UNAM's Faculty of Economics. Short vertical videos, gamification and adaptive learning. React Native frontend with NestJS backend.",
            stack: ['React Native', 'NestJS', 'PostgreSQL', 'MongoDB', 'MinIO', 'HLS'],
            screenshots: [],
          },
        ],
      },
      {
        title: 'Tech Lead — UNAM FI',
        period: 'Jan 2024 — Present',
        desc: 'Technical lead of the engineering faculty dev department. Built production infrastructure from scratch, led a small dev team, defined technical standards and deployment strategies.',
        stack: ['Jenkins', 'Docker', 'Gitea', 'Next.js', 'React'],
        deliverables: [
          {
            title: 'RAREB — Biometric Attendance System',
            desc: "Attendance system used daily by faculty at UNAM's Engineering School. Frontend connecting to .NET APIs integrated with facial and fingerprint recognition hardware.",
            stack: ['Next.js', 'NextAuth', '.NET', 'SQL Server'],
            screenshots: [
              '/projects/rareb/1.png',
              '/projects/rareb/2.png',
            ],
          },
          {
            title: 'Full Infrastructure & CI/CD Setup',
            desc: 'Built complete production infrastructure from scratch — server provisioning, virtual machine orchestration, SSH configuration and Jenkins automation. Pipelines cover automated testing before pull requests, build, Docker image tagging, registry push and zero-downtime deploy. Integrated automated alerts and workflow orchestration across environments.',
            stack: ['Jenkins', 'Docker', 'Linux', 'VMs', 'SSH', 'Nginx', 'Gitea'],
            screenshots: [],
          },
          {
            title: 'Private Docker Registry',
            desc: 'Self-hosted private Docker image registry with authentication, automated pruning and integration into CI/CD pipelines.',
            stack: ['Docker', 'Linux', 'Nginx'],
            screenshots: [],
          },
        ],
      },
      {
        title: 'Frontend Developer — UNAM FI',
        period: 'Jun 2022 — Jan 2024',
        desc: 'Built and maintained faculty web systems using React and TypeScript. Led frontend team — sprint coordination, code reviews, agile practices. Consumed and visualized data from multiple .NET APIs.',
        stack: ['React', 'TypeScript', 'Next.js', 'Redux', '.NET APIs'],
        deliverables: [
          {
            title: 'SICAE — Parking Management System',
            desc: 'Vehicle access control system for institutional staff. TAG-based entry, user registration, administrative reporting and incidence tracking.',
            stack: ['Next.js', 'React', '.NET', 'SQL Server'],
            screenshots: [
              '/projects/sicae/1.png',
              '/projects/sicae/2.png',
              '/projects/sicae/3.png',
            ],
          },
          {
            title: 'Baremetal Version Control — Gitea',
            desc: 'Set up and maintained a self-hosted Gitea instance on baremetal for institutional source code management. Configured repositories, permissions, webhooks and backup strategies.',
            stack: ['Gitea', 'Linux', 'Nginx', 'SSH'],
            screenshots: [],
          },
        ],
      },
      {
        title: 'Software Developer Internship — UNAM FI',
        period: 'Apr 2021 — Jun 2022',
        desc: 'First professional role. Maintained and updated institutional websites for the engineering faculty — bug fixes, content updates, performance improvements and accessibility enhancements across multiple faculty web properties.',
        stack: ['HTML', 'CSS', 'JavaScript', 'SQL', 'ASP.NET'],
        deliverables: [],
      },
      {
        title: 'Tech Lead — Dekids',
        period: 'Jan 2021 — Jan 2022',
        desc: 'Led technology at Dekids. Managed project delivery, coordinated development team and built the first version of the e-learning platform.',
        stack: ['Laravel', 'MySQL', 'WordPress', 'Agile'],
        deliverables: [
          {
            title: 'E-learning Platform (Beta)',
            desc: 'Designed and built beta e-learning platform for kids using Laravel, Eloquent ORM and MySQL. Full architecture and backend ownership from scratch.',
            stack: ['Laravel', 'MySQL', 'Eloquent', 'PHP'],
            screenshots: [],
          },
        ],
      },
    ],
    gx: -3.0, gy: 1.8,
    gw: 2.2, gd: 1.5,
    floors: 7, h: 175,
    col: '#f5a623',
  },
  {
    id: 'contact',
    label: 'Contact',
    sub: "Let's Build",
    tag: '05 — CONTACT',
    panelTitle: "Let's<br><span>Build</span>",
    body: 'Available for freelance projects globally. Fast async communication. I take full ownership from architecture to production.\n\nUpwork · LinkedIn · Remote friendly · MX timezone',
    stack: ['Full-Stack', 'DevOps', 'Next.js', 'Laravel', 'Docker', 'CI/CD'],
    items: [],
    gx: 1.8, gy: 2.2,
    gw: 1.8, gd: 1.4,
    floors: 4, h: 110,
    col: '#ffd060',
  },
]
